export enum IconTypes {
  CONTACTS = 'CONTACTS',
  CAMPAIGNS = 'CAMPAIGNS',
  WHATSAPP = 'WHATSAPP',
  SEND = 'SEND',
  REPORTS = 'REPORTS',
  AUDIT= 'AUDIT',
  BUY = 'BUY',
  SETTINGS = 'SETTINGS',
  IMPORT = 'IMPORT',
}
