export enum RechargeStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  FAILED = 'FAILED',
  REVERSED = 'REVERSED',
  HELD = 'HELD',
  INITIATED = 'INITIATED',
  EXPIRED = 'EXPIRED',
  ABANDONED = 'ABANDONED',
  CANCELLED = 'CANCELLED',
}
