export enum ModuleTypes {
  Organization = 'reports.common.organizations',
  User = 'common.user.users',
  Role = 'reports.common.roles',
  Permission = 'reports.common.permissions',
  Contact = 'contact.contacts',
  CustomField = 'common.contact.custom_fields',
  CustomValue = 'common.contact.custom_values',
  Campaign = 'common.campaign.campaigns',
  CampaignRule = 'common.campaign.campaign_rules',
  CampaignDispatch = 'common.campaign.campaign_dispatches',
  Provider = 'common.provider.providers',
  PaymentProvider = 'common.provider.payment_providers',
  Plan = 'common.plan.plans',
}
