#!/usr/bin/env bash

# Valida que el mensaje de commit tenga un formato adecuado
original_message="$(cat $1)"
# Elimina las líneas de comentarios que empiezan con #
message=$(echo "$original_message" | grep -v "^#")
min_length=10
max_length=200

if [ ${#message} -lt $min_length ]; then
  echo "⚠️ El mensaje de commit es demasiado corto (mínimo $min_length caracteres)"
  exit 1
fi

if [ ${#message} -gt $max_length ]; then
  echo "⚠️ El mensaje de commit es demasiado largo (máximo $max_length caracteres)"
  exit 1
fi

# Si llegamos aquí, el mensaje es válido
echo "✅ Mensaje de commit válido" 